---
title: "NodeMerging"
author: "Theodoros Papakonstantinou"
date: "2024-02-09"
output: html_document
---

```{r setup, include=FALSE}
rm(list=ls())
knitr::opts_chunk$set(echo = TRUE)
library(dplyr)
library(netmeta)
library(readxl)
source("studygraph.R")
```

Read mortality data

```{r readData, echo=T}
ACM_5_with_networks <- read_excel("data/ACM-5%-studyid1.xlsx")

#Insert variance
studyTable <- ACM_5_with_networks %>% 
  filter(!is.na(effect)) %>% 
  mutate(var = se^2)
```

Get all studies

```{r studies ,echo=T}
studyIds <- unique(studyTable$id)
```

There are `r length(studyIds)` studies

We now check which of the studies can be used

```{r studyReport, echo=T}
studyIds <- unique(studyTable$id)
errorstudies <- c()
warnmess <- c()
studyInconsistency <- data.frame()
studyGraphs <- lapply(studyIds, function(stid){
  res <- {}
  tryCatch({
    stgr <- fullGraph(stid, studyTable ,rand=F)
    res <- stgr
  },error = function(cond){
    # print(c("error in study",stid))
    errorstudies <<- c(errorstudies,stid)
    # message(conditionMessage(cond))
  })
  return(res)
})
SGs <- Filter(function(g){!is.null(g)},studyGraphs)
incgs <- Filter(function(g){g$inc & g$pvalue < 0.90},SGs)
lapply(incgs, function(g){plotEffects(g);plotDiffs(g)})
```

<!-- ### Analysis and forest plots -->

<!-- For each network, the network plot and the forest plots of logRRs using the random effects model are shown. We also give the heterogeneity standard deviation and the Pscores (the frequentist analogue of SUCRA) for each network. -->

<!-- ```{r Analysis} -->
<!-- lapply(1:7,function(netid){ -->
<!--   print(paste("Network ", netid, sep="")) -->
<!--   studyRows <- Reduce(function(acc, sid){ -->
<!--     tryCatch({ -->
<!--       sg <- fullGraph(sid,studyTable) -->
<!--       ns <- prepareStudyForNetwork(sg,netid,studyTable) -->
<!--       nsr <- rowsFromGraph(ns) -->
<!--       acc <- rbind(nsr,acc) -->
<!--     },error = function(cond){ -->
<!--     }) -->
<!--     return(acc) -->
<!--     },usableStudies,data.frame()) -->
<!--   net1 <- netmeta(TE=TE,seTE=seTE,treat1=treat1,treat2=treat2,studlab=studlab -->
<!--                   ,data=studyRows) -->
<!--   netgraph(net1) -->
<!--   forest(net1,pooled="random") -->
<!--   print(paste("tau: ",net1$tau, sep="")) -->
<!--   Pscores=netrank(net1, small.values = "good") -->
<!--   Pscores -->
<!-- }) -->
<!-- ``` -->
